export const exercises = {
  gobletSquat: {
    id: 'gobletSquat',
    name: 'goblet squat',
    equipment: 'kb',
    sets: 4,
    reps: 12,
    cue: 'KB seguro ao peito, cotovelos a apontar para baixo. desce até as coxas ficarem paralelas. talões no chão.',
    easier: 'menos profundidade',
    harder: 'pausa 2 seg em baixo',
    hipNote: 'anca esq: para quando sentires resistência, não forces a profundidade máxima',
  },
  bulgarianSplit: {
    id: 'bulgarianSplit',
    name: 'agachamento búlgaro',
    equipment: 'bodyweight',
    sets: 3,
    reps: 10,
    cue: 'pé traseiro elevado, desce o joelho traseiro em direção ao chão. tronco direito.',
    easier: 'reduz amplitude',
    harder: 'KB numa mão',
    hipNote: 'anca esq: reduz amplitude máxima',
  },
  hipHinge: {
    id: 'hipHinge',
    name: 'hip hinge KB',
    equipment: 'kb',
    sets: 3,
    reps: 10,
    cue: 'KB nas mãos, empurra a anca para trás mantendo as costas neutras. sentes puxão nos isquiotibiais.',
    easier: 'sem peso, só o movimento',
    harder: 'pausa 1 seg no fundo',
  },
  kbSwing: {
    id: 'kbSwing',
    name: 'swing kettlebell',
    equipment: 'kb',
    sets: 4,
    reps: 15,
cue: 'é um hip hinge, não um agachamento. empurra a anca para trás, projeta-a para a frente com força.',
    easier: '10 reps se cansativo',
    harder: '20 reps contínuas',
  },
  stepUp: {
    id: 'stepUp',
    name: 'step-up',
    equipment: 'bodyweight',
    sets: 3,
    reps: 12,
    cue: 'sobe com o pé inteiro na plataforma. empurra pelo calcanhar. não uses o joelho traseiro para ajudar.',
    easier: 'plataforma mais baixa',
    harder: 'KB numa mão',
  },
  pushUp: {
    id: 'pushUp',
    name: 'flexões',
    equipment: 'bodyweight',
    sets: 4,
    reps: 'máximo',
    cue: 'corpo rígido de cabeça aos calcanhares. cotovelos a 45 graus. desce até o peito quase tocar.',
    easier: 'joelhos no chão',
    harder: 'pausa 1 seg em baixo',
    fingerMod: 'apoio nos nós dos dedos',
  },
  pikePushUp: {
    id: 'pikePushUp',
    name: 'pike push-up',
    equipment: 'bodyweight',
    sets: 3,
    reps: 8,
    cue: 'ancas no ar em V invertido. desce a cabeça entre as mãos. trabalha os ombros.',
    easier: 'menos elevação das ancas',
    harder: 'pés elevados',
    fingerMod: 'apoio nos nós',
  },
  kbRow: {
    id: 'kbRow',
    name: 'remo KB um braço',
    equipment: 'kb',
    sets: 4,
    reps: 10,
    cue: 'joelho e mão do mesmo lado apoiados. puxa o cotovelo para o teto. coluna paralela ao chão.',
    easier: 'menos peso',
    harder: 'pausa 1 seg no topo',
    fingerMod: 'braço dir: pega suave, para se doer',
  },
  kbPress: {
    id: 'kbPress',
    name: 'press KB',
    equipment: 'kb',
    sets: 3,
    reps: 8,
    cue: 'KB à altura do ombro, empurra para cima em linha reta. core contraído.',
    easier: 'amplitude reduzida',
    harder: 'pausa 2 seg no topo',
    fingerMod: 'aguardar recuperação total do dedo',
  },
  plank: {
    id: 'plank',
    name: 'prancha frontal',
    equipment: 'bodyweight',
    sets: 4,
    duration: 40,
    cue: 'cotovelos diretamente abaixo dos ombros. aperta o core. não deixa as ancas subir nem descer.',
    easier: '30 seg',
    harder: 'levanta um pé alternado',
  },
  sidePlank: {
    id: 'sidePlank',
    name: 'prancha lateral',
    equipment: 'bodyweight',
    sets: 3,
    duration: 30,
    cue: 'corpo em linha reta da cabeça aos pés. anca não cai.',
    easier: 'joelho de apoio no chão',
    harder: 'levanta o braço de cima',
  },
  deadBug: {
    id: 'deadBug',
    name: 'dead bug',
    equipment: 'bodyweight',
    sets: 3,
    reps: 10,
    cue: 'costas coladas ao chão. baixa braço e perna opostos em simultâneo. não arqueia a lombar.',
    easier: 'só as pernas',
    harder: 'mais lento',
  },
  hollowBody: {
    id: 'hollowBody',
    name: 'hollow body hold',
    equipment: 'bodyweight',
    sets: 3,
    duration: 20,
    cue: 'lombar colada ao chão. pernas e braços esticados a 30 graus do chão. mantém.',
    easier: 'joelhos dobrados',
    harder: 'mais baixo',
  },
  russianTwist: {
    id: 'russianTwist',
    name: 'russian twist KB',
    equipment: 'kb',
    sets: 3,
    reps: 20,
    cue: 'tronco a 45 graus, pés no ar. roda o KB de lado a lado tocando no chão.',
    easier: 'pés no chão',
    harder: 'mais lento',
  },
};

export const warmupBJJ = [
  { name: 'rotações de anca', sets: 1, reps: 10, cue: 'círculos largos. anca esq: amplitude reduzida.', hipNote: 'amplitude reduzida' },
  { name: 'shrimping no sítio', sets: 1, reps: 10, cue: 'escapa a anca lateralmente como no BJJ. movimento fluido.' },
  { name: 'sit-out', sets: 2, reps: 8, cue: 'movimento contínuo, rodar a anca completamente.', fingerMod: 'punho fechado' },
  { name: 'grappler squat', sets: 1, reps: 10, cue: 'pés largos, alterna joelho ao chão. costas direitas.' },
  { name: 'rotações de ombro', sets: 1, reps: 12, cue: 'círculos para a frente e para trás. amplitude máxima.' },
  { name: 'bear crawl', sets: 1, duration: 20, cue: 'joelhos a 2cm do chão, costas planas.', fingerMod: 'punhos fechados' },
];

export const mobilidade = [
  { name: 'pigeon pose', sets: 1, duration: 30, cue: 'começa sempre pela anca esquerda. respira fundo, deixa afundar.', hipNote: 'sempre a primeira' },
  { name: 'figura 4 no chão', sets: 1, duration: 30, cue: 'tornozelo esq sobre joelho dir. puxa suavemente para o peito.', hipNote: 'anca esq sempre' },
  { name: 'gato-vaca', sets: 1, reps: 10, cue: 'inspira ao arquear, expira ao arredondar. lento e controlado.' },
  { name: 'hip flexor stretch', sets: 1, duration: 30, cue: 'joelho traseiro no chão, avança a anca. não arqueia as costas.' },
  { name: "world's greatest stretch", sets: 1, reps: 5, cue: 'amplitude reduzida na anca esq.', hipNote: 'amplitude reduzida' },
];

export const templates = {
  full_body: {
    name: 'full body',
    duration: 40,
    blocks: [
      { name: 'aquecimento bjj', type: 'warmup', exercises: warmupBJJ },
      { name: 'bloco A · superset', type: 'superset', exercises: [exercises.gobletSquat, exercises.pushUp] },
      { name: 'bloco B · superset', type: 'superset', exercises: [exercises.kbSwing, exercises.plank] },
      { name: 'bloco C', type: 'circuit', exercises: [exercises.hipHinge, exercises.kbRow] },
      { name: 'arrefecimento', type: 'cooldown', exercises: mobilidade.filter(m => ['pigeon pose','figura 4 no chão','hip flexor stretch'].includes(m.name)) },
    ],
  },
  upper_focus: {
    name: 'upper focus',
    duration: 35,
    blocks: [
      { name: 'aquecimento', type: 'warmup', exercises: mobilidade.filter(m => ['gato-vaca'].includes(m.name)) },
      { name: 'bloco A', type: 'superset', exercises: [exercises.pushUp, exercises.kbRow] },
      { name: 'bloco B', type: 'superset', exercises: [exercises.pikePushUp, exercises.deadBug] },
      { name: 'core', type: 'circuit', exercises: [exercises.hollowBody, exercises.russianTwist] },
      { name: 'arrefecimento', type: 'cooldown', exercises: mobilidade.filter(m => ['pigeon pose','figura 4 no chão'].includes(m.name)) },
    ],
  },
  lower_focus: {
    name: 'lower focus',
    duration: 40,
    blocks: [
      { name: 'aquecimento', type: 'warmup', exercises: warmupBJJ.filter(w => ['rotações de anca','grappler squat','shrimping no sítio'].includes(w.name)) },
      { name: 'bloco A', type: 'superset', exercises: [exercises.gobletSquat, exercises.hipHinge] },
      { name: 'bloco B', type: 'superset', exercises: [exercises.kbSwing, exercises.bulgarianSplit] },
      { name: 'core', type: 'circuit', exercises: [exercises.plank, exercises.sidePlank] },
      { name: 'arrefecimento', type: 'cooldown', exercises: mobilidade },
    ],
  },
  recovery: {
    name: 'recovery',
    duration: 15,
    blocks: [
      { name: 'mobilidade', type: 'cooldown', exercises: mobilidade },
    ],
  },
  bjj_prep: {
    name: 'bjj prep',
    duration: 25,
    blocks: [
      { name: 'aquecimento bjj', type: 'warmup', exercises: warmupBJJ },
      { name: 'core', type: 'circuit', exercises: [exercises.plank, exercises.deadBug, exercises.hollowBody] },
      { name: 'mobilidade', type: 'cooldown', exercises: mobilidade.filter(m => ['pigeon pose','figura 4 no chão'].includes(m.name)) },
    ],
  },
};
